"""Add paynow_reference and poll_url to payments

Revision ID: 1c1ffeab9640
Revises: f1ab5053e045
Create Date: 2026-02-26 12:33:28.099888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1ffeab9640'
down_revision: Union[str, None] = 'f1ab5053e045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paynow_reference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('poll_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('poll_url')
        batch_op.drop_column('paynow_reference')

    # ### end Alembic commands ###
